### ISSUE TITLE
PostgreSQL Enum Arrays don't convert to Javascript Array

### ISSUE THREAD

**Issue by andrewcirel** [brianc/node-postgres-docs#171]
When I retrieve a profile (shown below) from the profiles table you will notice that the 2 enumerated arrays lookingForCountries  and lookingForReligions haven't been converted to javascript arrays, but the character varying array photos has.
{
  nickname: 'Cool Man Test Account',
  description: 'I am the coolest man alive',
  age: 40,
  location: 'Oxford',
  gender: 'Male',
  sexuality: 'Straight',
  religion: 'Christianity',
  alcohol: 'Yes',
  smoking: 'No',
  lookingForGender: 'Female',
  lookingForSexuality: 'Straight',
  country: 'Any',
  interests: '0',
  lookingForCountries: '{"United Kingdom",Albania}',
  lookingForReligions: '{Agnostism,Atheism}',
  photos: [ '', '', '', '', '' ],
  lookingForFromAge: '34',
  lookingForToAge: 40
}
I can provide all of the table definitions, enum definitions and javascript code if you like, but this should be easy to replicate as you just create an enum type, create a column of enum array and try to retrieve the table row from Javascript.

**Comment by boromisp** [comment]
See: https://github.com/brianc/node-pg-types/issues/56

**Comment by andrewcirel** [comment]
Thanks for the information.
I am surprised the driver needs to query the database to convert an array into another array, but still.
The driver actually returns the enum array as a string so I've decided to do the following:
profile.lookingForCountries = profile.lookingForCountries.replace('{', '').replace('}', '').replaceAll('\"', '').split(',')
It is a bit long-winded, but it works.

**Comment by charmander** [comment]
> I am surprised the driver needs to query the database to convert an array into another array

The issue is more that it can’t know the text represents any kind of array at all without looking up the type code.

Anyway, instead of doing those replacements – which is a bit of a hack – you should either cast `::text[]` in your query or at least use [postgres-array](https://www.npmjs.com/package/postgres-array)’s `parse`. (It’s already used by pg, not an extra dependency.)
