### ISSUE TITLE
Uncaught reference error : process is not defined

### ISSUE THREAD

**Issue by fibag21** [brianc/node-postgres-docs#178]
Hi,

I'm trying to use pg to connect to and query a PostgreSQL DB. Using a node.js environment. upon loading the page in the browser, I receive this "uncaught reference error : process is not defined" in pg/lib/defaults.js on line 8.

Package built with yarn,

Any hint ?
Thanks

**Comment by charmander** [comment]
Sounds like your code is running in a browser environment instead of a Node.js environment. It’s not really possible to say without details, but it’s not a pg-side issue anyway.
