### ISSUE TITLE
PGDATABASE=process.env.USER or PGDATABASE=process.env.DATABASE?

### ISSUE THREAD

**Issue by Bam92** [brianc/node-postgres-docs#183]
I am wondering if this is typo or it's normal. For me, it could be `PGDATABASE=process.env.DATABASE` instead of  `PGDATABASE=process.env.USER` in `/1-connecting.mdx` file.

**Comment by charmander** [comment]
`USER` is the current OS user, and it is indeed used as the default database name when neither `PGDATABASE` nor `PGUSER` is specified; `DATABASE` isn’t a thing.
